config/routes.rb
Ucnparking::Application.routes.draw do
  resources :places, only: [:index, :show]

  root to: 'places#index'

end

app/models/parking_place.rb
class ParkingPlace
  # extend Savon::Model

  # client do
  #   wsdl.document = File.expand_path("../ParkService.wsdl", __FILE__)
  #   wsdl.endpoint = "http://83.90.235.21:8080/ParkService/services/ParkService/"
  #   http.auth.digest ENV['AK_AUTH_USER'], ENV['AK_AUTH_PASS']
  #   config.pretty_print_xml = true
  # end

  # Accessor methods
  # attr_accessor :name
  # attr_accessor :open?
  # attr_accessor :payment_active?
  # attr_accessor :status_park_place
  # attr_accessor :longitude
  # attr_accessor :latitude
  # attr_accessor :max_count
  # attr_accessor :free_count

  # Requests
  def self.all
    response = client.request(:park_places) do
      soap.body = {
        password: ENV['AK_SOAP_PASS'],
        'ClientRequestHandle' => 'ucn',
        'RequestTime' => DateTime.now,
        :order! => ['Password', 'ClientRequestHandle', 'RequestTime']
      }
    end

    parking_places = []
    if response.http.code == 200
      response_content = response[:park_places_response]
      names = response_content[:name]
      is_opens = response_content[:is_open]
      is_payment_actives = response_content[:is_payment_active]
      status_park_places = response_content[:status_park_place]
      longitudes = response_content[:longitude]
      latitudes = response_content[:latitude]
      max_counts = response_content[:max_count]
      free_counts = response_content[:free_count]

      names.each_with_index do |n, i|
        place = ParkingPlace.new
        place.name = n
        place.is_open = is_opens[i]
        place.is_payment_active = is_payment_actives[i]
        place.status_park_place = status_park_places[i]
        place.longitude = longitudes[i]
        place.latitude = latitudes[i]
        place.max_count = max_counts[i]
        place.free_count = free_counts[i]

        parking_places << place
      end
    end
    parking_places
  end

  def to_s
    "#{@name} #{@free_count}/#{@max_count}"
  end

  def to_xml
    hash = {}
    hash[:name] = name
    hash[:is_open] = is_open
    hash.to_xml
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  rescue_from(Savon::Error, Errno::ENETUNREACH, Errno::EHOSTUNREACH,
    HTTPClient::ConnectTimeoutError, with: :soap_error)

  # GET places
  # GET places.json
  # GET places.xml
  def index
    if params[:skip_memcache]
      logger.debug 'Skipping memcache'
      @parking_places = fetch_parking_places
    else
      logger.debug 'Using memcache'
      @parking_places = Rails.cache.fetch('parking_places') do
        fetch_parking_places
      end
    end

    respond_to do |format|
      format.html
      format.json { render json: @parking_places }
      format.xml { render xml: @parking_places }
    end
  end

  # GET /places/name
  # GET /places/name.json
  # GET /places/name.xml
  def show
    @parking_place_info = {}

    client = setup_savon
    message = {
      client_request: {
        password: ENV['AK_SOAP_PASS'],
        client_request_handle: 'ucn',
        request_time: DateTime.now
        },
        park_place_name: params[:id]
      }
    response = client.call(:park_places_info, message: message)  # Giver Status_Main -92
    # response = client.call(:park_place_pay_periods, message: message)  # Giver Status -91
    # response = client.call(:park_place_closed_periods, message: message)  # Giver Status -91
    # response = client.call(:park_places_lane_info, message: message)  # Giver svar
    # response = client.call(:single_space, message: message)  # Giver Status_Main 0

    if response.success?
      @parking_place_info = response.body[:park_places_info_response]
      # @parking_place_info = response.body[:park_places_lane_info_response]
      @parking_place_info.delete(:'@xmlns:ns1') # Remove illegal key for XML rendering
    end

    respond_to do |format|
      format.html
      format.json { render json: @parking_place_info }
      format.xml { render xml: @parking_place_info }
    end
  end

  private

  def fetch_parking_places
    parking_places = []

    client = setup_savon
    message = {
      password: ENV['AK_SOAP_PASS'],
      client_request_handle: 'ucn',
      request_time: DateTime.now
    }
    response = client.call(:park_places, message: message)

    if response.success?
      response_content = response.body[:park_places_response]
      names = response_content[:name]
      is_opens = response_content[:is_open]
      is_payment_actives = response_content[:is_payment_active]
      status_park_places = response_content[:status_park_place]
      longitudes = response_content[:longitude]
      latitudes = response_content[:latitude]
      max_counts = response_content[:max_count]
      free_counts = response_content[:free_count]

      names.each_with_index do |n, i|
        place = Hash.new
        place[:name] = n
        place[:is_open] = is_opens[i]
        place[:is_payment_active] = is_payment_actives[i]
        place[:status_park_place] = status_park_places[i]
        place[:longitude] = longitudes[i]
        place[:latitude] = latitudes[i]
        place[:max_count] = max_counts[i]
        place[:free_count] = free_counts[i]

        parking_places << place
      end
    end
    parking_places
  end

  def setup_savon
    wsdl_path = File.expand_path('../ParkService.wsdl', __FILE__)
    Savon.client do
      log false
      log_level :debug
      pretty_print_xml true
      wsdl wsdl_path
      endpoint ENV['AK_ENDPOINT']
      digest_auth ENV['AK_AUTH_USER'], ENV['AK_AUTH_PASS']
      convert_request_keys_to :camelcase
    end
  end

  def soap_error(error)
    logger.debug "ERROR: #{error.message}"
    respond_to do |format|
      format.html
      format.json { render json: [] }
      format.xml { render xml: [] }
    end
  end
end

app/views/layouts/application.html.erb
<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "UCN Parking" %></title>
  <meta name="description" content="">
  <meta name="author" content="">
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= yield(:head) %>
</head>
<body>
  <div id="main" role="main">
    <div class="container">
      <div class="content">

        <%= yield %>

        <footer class="footer">
          <div class="row">
            Using memcache: <%= params[:skip_memcache] ? 'No' : 'Yes' %>
          </div>
        </footer>

      </div>
    </div> <!--! end of .container -->
  </div> <!--! end of #main -->
</body>
</html>

app/views/places/index.html.erb
<div class="row">
	<h1>Aalborg Parking Places</h1>

	<table class="table">
		<thead>
			<tr>
				<th>Name</th>
				<th>Vacant</th>
				<th>Spaces</th>
				<th>Open</th>
				<th>Payment Active</th>
				<th>Status</th>
				<th>Longitude</th>
				<th>Latitude</th>
			</tr>
		</thead>
		<tbody>
			<% @parking_places.each do |place| %>
			<tr>
				<td><%= link_to place[:name], place_path(id:place[:name]) %></td>
				<td class="vacant"><%= place[:free_count] %></td>
				<td class="max-spaces"><%= place[:max_count] %></td>
				<td><%= place[:is_open] %></td>
				<td><%= place[:is_payment_active] %></td>
				<td><%= place[:status_park_place] %></td>
				<td><%= place[:latitude] %></td>
				<td><%= place[:longitude] %></td>
			</tr>
			<% end %>
		</tbody>
	</table>

	<%= link_to 'JSON', places_path(format: :json), class:"btn btn-info btn-small" %>
	<%= link_to 'XML', places_path(format: :xml), class:"btn btn-info btn-small" %>
</div>

app/views/places/show.html.erb
<h1><%= @parking_place_info[:name] %></h1>

<p><strong>Status</strong> <%= @parking_place_info[:status_park_place] %></p>
<p><strong>Description</strong> <%= @parking_place_info[:description] %></p>
<p><strong>Public Description</strong> <%= @parking_place_info[:description_public] %></p>
<p><strong>Open</strong> <%= @parking_place_info[:is_open] %></p>
<p><strong>Handicap Spaces</strong> <%= @parking_place_info[:count_of_handicap_places] %></p>
<p><strong>Charging Stations</strong> <%= @parking_place_info[:count_of_charging_stations] %></p>
<p><strong>Opening Hours</strong> <%= @parking_place_info[:opening_time_description] %></p>
<p><strong>Pay Period</strong> <%= @parking_place_info[:pay_period_description] %></p>
<p><strong>Price</strong> <%= @parking_place_info[:price_description] %></p>
<p><strong>Free Period</strong> <%= @parking_place_info[:price_free_period] %></p>
<p><strong>Price Per Minute</strong> <%= @parking_place_info[:price_per_minut] %></p>

<% if @parking_place_info[:name] %>
<%= link_to 'JSON', place_path(id:@parking_place_info[:name], format: :json), class:"btn btn-info btn-small" %>
<%= link_to 'XML', place_path(id:@parking_place_info[:name], format: :xml), class:"btn btn-info btn-small" %>
<% end %>